routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Ecommerce\FrontController@index')->name('front.index');
Route::get('/about-us', 'Ecommerce\FrontController@about')->name('front.about');
Route::get('/product', 'Ecommerce\FrontController@product')->name('front.product');
Route::get('/category/{slug}', 'Ecommerce\FrontController@categoryProduct')->name('front.category');
Route::get('/product/{id}', 'Ecommerce\FrontController@show')->name('front.show_product');
Route::get('/product/variant/{var}', 'Ecommerce\FrontController@getVariantInfo')->name('front.show_product.variant');

Route::get('/find-order', 'Ecommerce\FrontController@findOrder')->name('front.find_order');
Route::post('/find-order', 'Ecommerce\FrontController@showOrder')->name('front.find_order.show');

Route::post('cart', 'Ecommerce\CartController@addToCart')->name('front.cart');
Route::get('/cart', 'Ecommerce\CartController@listCart')->name('front.list_cart');
Route::post('/cart/update-reg', 'Ecommerce\CartController@updateSeamlessReg')->name('front.update_seamless_reg');
Route::post('/cart/update-unreg', 'Ecommerce\CartController@updateSeamlessUnreg')->name('front.update_seamless_unreg');
Route::post('/cart/update', 'Ecommerce\CartController@updateCart')->name('front.update_cart');
Route::get('/cart/remove/{id}', 'Ecommerce\CartController@removeFromCart')->name('front.remove_from_cart');

Route::get('/checkout', 'Ecommerce\CartController@checkout')->name('front.checkout');
Route::post('/checkout', 'Ecommerce\CartController@processCheckout')->name('front.store_checkout');
Route::get('/checkout/{invoice}', 'Ecommerce\CartController@checkoutFinish')->name('front.finish_checkout');

Route::group(['prefix' => 'member', 'namespace' => 'Ecommerce'], function() {
    Route::get('login', 'LoginController@loginForm')->name('customer.login');
    Route::post('login', 'LoginController@login')->name('customer.post_login');
    Route::get('verify/{token}', 'FrontController@verifyCustomerRegistration')->name('customer.verify');
    Route::post('verify', 'FrontController@setPassword')->name('customer.set_password');
    Route::get('signup', 'SignupController@signupForm')->name('customer.signup');
    Route::post('signup', 'SignupController@signup')->name('customer.post_signup');
    Route::get('orders/x/{invoice}', 'OrderController@view')->name('customer.view_order_unregistered');
    Route::get('orders/x/pdf/{invoice}', 'OrderController@pdf')->name('customer.order_pdf_unregistered');
    Route::post('orders/x/accept', 'OrderController@acceptOrder')->name('customer.order_accept_unregistered');
    Route::get('orders/x/cancel/{invoice}', 'OrderController@cancelOrder')->name('customer.order_cancel_unregistered');
    Route::get('payment/x', 'OrderController@paymentForm')->name('customer.paymentForm_unregistered');
    Route::post('payment/x', 'OrderController@storePayment')->name('customer.savePayment_unregistered');
    Route::post('/init-payment', 'OrderController@setPaymentDestination')->name('customer.set_payment_destination');

    Route::group(['middleware' => 'customer'], function() {
        Route::get('dashboard', 'LoginController@dashboard')->name('customer.dashboard');
        Route::get('logout', 'LoginController@logout')->name('customer.logout');

        Route::get('orders', 'OrderController@index')->name('customer.orders');
        Route::get('orders/a/{invoice}', 'OrderController@view')->name('customer.view_order');
        Route::get('orders/a/pdf/{invoice}', 'OrderController@pdf')->name('customer.order_pdf');
        Route::post('orders/a/accept', 'OrderController@acceptOrder')->name('customer.order_accept');
        Route::get('orders/a/cancel/{invoice}', 'OrderController@cancelOrder')->name('customer.order_cancel');
        Route::get('orders/return/{invoice}', 'OrderController@returnForm')->name('customer.order_return');
        Route::put('orders/return/{invoice}', 'OrderController@processReturn')->name('customer.return');

        Route::get('payment/a', 'OrderController@paymentForm')->name('customer.paymentForm');
        Route::post('payment/a', 'OrderController@storePayment')->name('customer.savePayment');

        Route::get('setting', 'FrontController@customerSettingForm')->name('customer.settingForm');
        Route::post('setting', 'FrontController@customerUpdateProfile')->name('customer.setting');
    });
});

Auth::routes();

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/manage', 'HomeController@homeManagement')->name('admin.home_management');

    Route::delete('/delete/{id}', 'HomeController@deleteFromSlider')->name('admin.home_management.slider.delete');
    Route::get('/manage/slider/add', 'HomeController@viewAddSlider')->name('admin.home_management.slider.view_add');
    Route::post('/manage/slider/add', 'HomeController@addToSlider')->name('admin.home_management.slider.add');
    Route::get('/manage/slider/show/{id}', 'HomeController@show')->name('admin.home_management.slider.show');
    Route::get('/manage/slider/edit/{id}', 'HomeController@viewEditSlider')->name('admin.home_management.slider.view_edit');
    Route::post('/manage/slider/edit', 'HomeController@editSlider')->name('admin.home_management.slider.edit');

    Route::delete('/{id}', 'HomeController@deleteFromFeatured')->name('admin.home_management.featured.delete');
    Route::post('/manage/featured/add', 'HomeController@addToFeatured')->name('admin.home_management.featured.add');

    Route::resource('admin', 'AdminController');

    
    Route::get('/product_variant/create/{id}', 'ProductVariantController@createVariant')->name('product_variant.create_variant');
    Route::get('/product_variant/get/{id}', 'ProductVariantController@get')->name('product_variant.get');
    Route::resource('category', 'CategoryController')->except(['create', 'show']);
    Route::resource('product', 'ProductController');
    Route::resource('product_variant', 'ProductVariantController')->except(['index', 'create', 'show']);

    Route::group(['prefix' => 'orders'], function() {
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('/orders_pending', 'OrderController@ordersPending')->name('orders.orders_pending');
        Route::get('/orders_done', 'OrderController@ordersDone')->name('orders.orders_done');
        Route::get('/{invoice}', 'OrderController@view')->name('orders.view');
        Route::get('/pending/{invoice}', 'OrderController@pendingPayment')->name('orders.make_pending');
        Route::get('/cancel/{invoice}', 'OrderController@cancelPayment')->name('orders.cancel_payment');
        Route::get('/payment/{invoice}', 'OrderController@acceptPayment')->name('orders.approve_payment');
        Route::post('/shipping', 'OrderController@shippingOrder')->name('orders.shipping');
        Route::get('/finish/{invoice}', 'OrderController@finishOrder')->name('orders.make_done');
        Route::delete('/{id}', 'OrderController@destroy')->name('orders.destroy');
        Route::get('/return/{invoice}', 'OrderController@return')->name('orders.return');
        Route::post('/return', 'OrderController@approveReturn')->name('orders.approve_return');
    });

    Route::group(['prefix' => 'reports'], function() {
        Route::get('/keuangan', 'HomeController@financeReport')->name('report.finance');
        Route::get('/product_statistic', 'HomeController@productStatistic')->name('report.product_statistic');
        Route::get('/order/pdf/{daterange}', 'HomeController@orderReportPdf')->name('report.order_pdf');
        Route::get('/return', 'HomeController@returnReport')->name('report.return');
        Route::get('/return/pdf/{daterange}', 'HomeController@returnReportPdf')->name('report.return_pdf');
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    protected $guarded = [];
    protected $appends = ['status_label'];

    public function getStatusLabelAttribute()
    {
        if ($this->status == 0) {
            return '<span class="badge badge-secondary">Draft</span>';
        } else {
            return '<span class="badge badge-success">Aktif</span>';
        }
    }

    public function setSlugAttribute($value) {
        if (static::whereSlug($slug = Str::slug($value))->exists()) {
            $slug = $this->incrementSlug($slug);
        }    
        $this->attributes['slug'] = $slug;
    }

    public function incrementSlug($slug) {
        $original = $slug;
        $count = 2;
        while (static::whereSlug($slug)->exists()) {
            $slug = "{$original}-" . $count++;
        }
        return $slug;
    }
    
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function variant()
    {
        return $this->hasMany(ProductVariant::class)->orderBy('price', 'ASC');;
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use App\Product;
use App\ProductVariant;
use App\Category;
use File;
use App\Jobs\ProductJob;
use App\Jobs\MarketplaceJob;

class ProductController extends Controller
{
    public function index()
    {
        if (Auth::user()->user_type_id == 1) {
            $product = Product::with(['category', 'variant'])->orderBy('created_at', 'DESC');
            $category = Category::orderBy('name', 'DESC')->get();
            $variant = ProductVariant::with(['product'])->get();
            if (request()->q != '') {
                $product = $product->where('name', 'LIKE', '%' . request()->q . '%');
            }
            $product = $product->paginate(10);
            return view('products.index', compact('product', 'category', 'variant'));
        }
    }

    public function create()
    {
        if (Auth::user()->user_type_id == 1) {
            $category = Category::orderBy('name', 'DESC')->get();
            return view('products.create', compact('category'));
        }
    }

    public function store(Request $request)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'category_id' => 'required|exists:categories,id',
                'name' => 'required|string|max:100',
                'description' => 'required',
                'status' => 'required|boolean',
                'image' => 'required|image|mimes:png,jpeg,jpg'
            ]);
            
            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $filename = time() . Str::slug($request->name) . '.' . $file->getClientOriginalExtension();
                $file->storeAs('public/products', $filename);

                $product = Product::create([
                    'category_id' => $request->category_id,
                    'name' => $request->name,
                    'slug' => $request->name,
                    'description' => $request->description,
                    'status' => $request->status,
                    'image' => $filename
                ]);

                $product_id = $product->id;

                $this->storeVariant($product_id, $request);

                return redirect(route('product.index'))->with(['success' => 'Produk dan Varian Baru Ditambahkan!']);
            }
        }
    }
    
    public function show($id)
    {
        $product = Product::where('id', $id)->with('variant', 'category')->first();
        return view('products.show', compact('product'));
    }

    public function storeVariant($product_id, Request $request)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'name_var' => 'required|string',
                'price' => 'required|integer',
                'weight' => 'required|integer',
                'minimum_stock' => 'required|integer',
                'stock' => 'required|integer',
                'image' => 'required|image|mimes:png,jpeg,jpg'
            ]);

            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $filename = time() . Str::slug($request->name_var) . '.' . $file->getClientOriginalExtension();
                $file->storeAs('public/variants', $filename);

                $product = ProductVariant::create([
                    'product_id' => $product_id,
                    'name' => $request->name_var,
                    'slug' => $request->name_var,
                    'price' => $request->price,
                    'weight' => $request->weight,
                    'minimum_stock' => $request->minimum_stock,
                    'stock' => $request->stock,
                    'image' => $filename
                ]);
            }
        }
    }

    public function edit($id)
    {
        if (Auth::user()->user_type_id == 1) {
            $product = Product::find($id);
            $category = Category::orderBy('name', 'DESC')->get();
            return view('products.edit', compact('product', 'category'));
        }
    }

    public function update(Request $request, $id)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'category_id' => 'required|exists:categories,id',
                'name' => 'required|string',
                'description' => 'required',
                'status' => 'required|boolean',
                'image' => 'nullable|image|mimes:png,jpeg,jpg'
            ]);

            $product = Product::find($id);
            $filename = $product->image;
            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $filename = time() . Str::slug($request->name) . '.' . $file->getClientOriginalExtension();
                $file->storeAs('public/products', $filename);
                File::delete(storage_path('app/public/products/' . $product->image));
            }

            $product->update([
                'category_id' => $request->category_id,
                'name' => $request->name,
                'description' => $request->description,
                'status' => $request->status,
                'image' => $filename
            ]);
            return redirect(route('product.index'))->with(['success' => 'Data Produk Diperbaharui!']);
        }
    }

    public function destroy($id)
    {
        if (Auth::user()->user_type_id == 1) {
            $product = Product::find($id);
            File::delete(storage_path('app/public/products/' . $product->image));
            $product->delete();

            $product_variants = ProductVariant::where('product_id', $id)->get();

            foreach($product_variants as $v) {
                $v->delete();
            }
            return redirect(route('product.index'))->with(['success' => 'Produk Sudah Dihapus!']);
        }
    }

    public function massUploadForm()
    {
        if (Auth::user()->user_type_id == 1) {
            $category = Category::orderBy('name', 'DESC')->get();
            return view('products.bulk', compact('category'));
        }
    }

    public function massUpload(Request $request)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'category_id' => 'required|exists:categories,id',
                'file' => 'required|mimes:xlsx'
            ]);

            if ($request->hasFile('file')) {
                $file = $request->file('file');
                $filename = time() . '-product.' . $file->getClientOriginalExtension();
                $file->storeAs('public/uploads', $filename);

                ProductJob::dispatch($request->category_id, $filename);
                return redirect()->back()->with(['success' => 'Upload Produk Dijadwalkan']);
            }
        }
    }

    public function uploadViaMarketplace(Request $request)
    {
        $this->validate($request, [
            'marketplace' => 'required|string',
            'username' => 'required|string'
        ]);

        MarketplaceJob::dispatch($request->username, 10);
        return redirect()->back()->with(['success' => 'Produk Dalam Antrian']);
    }

    
}

resources/views/products/variant/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Tambah Varian</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/administrator/home">Home</a></li>
        <li class="breadcrumb-item"><a href="/administrator/product">Produk</a></li>
        <li class="breadcrumb-item active">Tambah Varian</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-4">
                    <div>
                        <a href="/administrator/product">
                            <button class="btn btn-default mb-3"><i class="fa fa-chevron-circle-left"></i> Kembali</button>
                        </a>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Varian Baru</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('product_variant.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="product_id">Produk</label>
                                    <select name="product_id" class="form-control">
                                        <option value="{{ $product->id }}" selected>{{ $product->name }}</option>
                                    </select>
                                    <p class="text-danger">{{ $errors->first('product_id') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="name">Nama Varian</label>
                                    <input type="text" name="name" class="form-control" value="{{ old('name') }}" required>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="price">Harga</label>
                                    <input type="number" name="price" class="form-control" value="{{ old('price') }}" required>
                                    <p class="text-danger">{{ $errors->first('price') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="weight">Berat</label>
                                    <input type="number" name="weight" class="form-control" value="{{ old('weight') }}" required>
                                    <p class="text-danger">{{ $errors->first('weight') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="stock">Stok Minimum</label>
                                    <input type="number" name="minimum_stock" class="form-control" value="{{ old('minimum_stock') }}" required>
                                    <p class="text-danger">{{ $errors->first('minimum_stock') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="stock">Stok</label>
                                    <input type="number" name="stock" class="form-control" value="{{ old('stock') }}" required>
                                    <p class="text-danger">{{ $errors->first('stock') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="image">Foto Varian</label>
                                    <input type="file" name="image" class="form-control" value="{{ old('image') }}" required>
                                    <p class="text-danger">{{ $errors->first('image') }}</p>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Tambah</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

@section('js')
<script>
    $('select').select2({
        theme: 'bootstrap4'
    });
</script>
@endsection

resources/views/products/variant/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Edit Varian Produk</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Varian Produk</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <form action="{{ route('product_variant.update', $variant->id) }}" method="post" enctype="multipart/form-data" >
                @csrf
                @method('PUT')

                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Edit Varian Produk</h4>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="product_id">Produk</label>
                                    <select name="product_id" class="form-control">
                                        <option value="">Pilih</option>
                                        @foreach ($product as $row)
                                        <option value="{{ $row->id }}" {{ $variant->product_id == $row->id ? 'selected':'' }}>{{ $row->name }}</option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('product_id') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="name">Nama Varian</label>
                                    <input type="text" name="name" class="form-control" value="{{ $variant->name }}" required>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="price">Harga</label>
                                    <input type="number" name="price" class="form-control" value="{{ $variant->price }}" required>
                                    <p class="text-danger">{{ $errors->first('price') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="weight">Berat</label>
                                    <input type="number" name="weight" class="form-control" value="{{ $variant->weight }}" required>
                                    <p class="text-danger">{{ $errors->first('weight') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="minimum_stock">Stok Minimum</label>
                                    <input type="number" name="minimum_stock" class="form-control" value="{{ $variant->minimum_stock }}" required>
                                    <p class="text-danger">{{ $errors->first('minimum_stock') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="stock">Stok</label>
                                    <input type="number" name="stock" class="form-control" value="{{ $variant->stock }}" required>
                                    <p class="text-danger">{{ $errors->first('stock') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="image">Foto Produk</label>
                                    <br>
                                    <img src="{{ asset('storage/variants/' . $variant->image) }}" width="100px" height="100px" alt="{{ $variant->name }}">
                                    <hr>
                                    <input type="file" name="image" class="form-control">
                                    <p><strong>Biarkan kosong jika tidak ingin mengganti gambar</strong></p>
                                    <p class="text-danger">{{ $errors->first('image') }}</p>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm" id="submit_update" onclick="return confirm('Ubah Data?')">Update</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
@endsection

@section('js')
<script>
    $('select').select2({
        theme: 'bootstrap4'
    });
</script>
@endsection

resources/views/products/variant/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>List Produk</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Produk</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List Produk</h4>
                        </div>
                        <div class="card-body">
                            @if (session('success'))
                                <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            @if (session('error'))
                                <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif

                            <span><a href="{{ route('product.create') }}"><button class="btn btn-primary mb-3 float-left">Tambah Produk</button></a></span>
                            <form action="{{ route('product_variant.index') }}" method="get">
                                <div class="input-group mb-3 col-md-3 float-right">
                                    <input type="text" name="q" class="form-control" placeholder="Cari..." value="{{ request()->q }}">
                                    <div class="input-group-append">
                                        <button class="btn btn-secondary" type="button">Cari</button>
                                    </div>
                                </div>
                            </form>
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nama Produk</th>
                                            <th>Nama Varian</th>
                                            <th>Stok</th>
                                            <th>Harga</th>
                                            <th>Berat</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($variant as $row)
                                        <tr>
                                            <td>{{ $row->product['name'] }}</td>
                                            <td>
                                                {{ $row->name }}
                                            </td>
                                            <td>{{ $row->stock }}</td>
                                            <td>Rp {{ number_format($row->price) }}</td>
                                            <td>{{ $row->weight }}</td>
                                            <td>
                                                <form action="{{ route('product_variant.destroy', $row->id) }}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="#" class="btn btn-success btn-sm">Detil</a>
                                                    <a href="{{ route('product_variant.edit', $row->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                                    <button class="btn btn-danger btn-sm" onclick="return confirm('Hapus Varian?')">Hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="6" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                            {!! $variant->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

@section('js')
<script>
    $('select').select2({
        theme: 'bootstrap4'
    });

    const table = document.querySelector('table');

    let headerCell = null;

    for (let row of table.rows) {
    const firstCell = row.cells[0];
    
    if (headerCell === null || firstCell.innerText !== headerCell.innerText) {
        headerCell = firstCell;
    } else {
        headerCell.rowSpan++;
        firstCell.remove();
        }
    }
</script>
@endsection