routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Ecommerce\FrontController@index')->name('front.index');
Route::get('/about-us', 'Ecommerce\FrontController@about')->name('front.about');
Route::get('/product', 'Ecommerce\FrontController@product')->name('front.product');
Route::get('/category/{slug}', 'Ecommerce\FrontController@categoryProduct')->name('front.category');
Route::get('/product/{id}', 'Ecommerce\FrontController@show')->name('front.show_product');
Route::get('/product/variant/{var}', 'Ecommerce\FrontController@getVariantInfo')->name('front.show_product.variant');

Route::get('/find-order', 'Ecommerce\FrontController@findOrder')->name('front.find_order');
Route::post('/find-order', 'Ecommerce\FrontController@showOrder')->name('front.find_order.show');

Route::post('cart', 'Ecommerce\CartController@addToCart')->name('front.cart');
Route::get('/cart', 'Ecommerce\CartController@listCart')->name('front.list_cart');
Route::post('/cart/update-reg', 'Ecommerce\CartController@updateSeamlessReg')->name('front.update_seamless_reg');
Route::post('/cart/update-unreg', 'Ecommerce\CartController@updateSeamlessUnreg')->name('front.update_seamless_unreg');
Route::post('/cart/update', 'Ecommerce\CartController@updateCart')->name('front.update_cart');
Route::get('/cart/remove/{id}', 'Ecommerce\CartController@removeFromCart')->name('front.remove_from_cart');

Route::get('/checkout', 'Ecommerce\CartController@checkout')->name('front.checkout');
Route::post('/checkout', 'Ecommerce\CartController@processCheckout')->name('front.store_checkout');
Route::get('/checkout/{invoice}', 'Ecommerce\CartController@checkoutFinish')->name('front.finish_checkout');

Route::group(['prefix' => 'member', 'namespace' => 'Ecommerce'], function() {
    Route::get('login', 'LoginController@loginForm')->name('customer.login');
    Route::post('login', 'LoginController@login')->name('customer.post_login');
    Route::get('verify/{token}', 'FrontController@verifyCustomerRegistration')->name('customer.verify');
    Route::post('verify', 'FrontController@setPassword')->name('customer.set_password');
    Route::get('signup', 'SignupController@signupForm')->name('customer.signup');
    Route::post('signup', 'SignupController@signup')->name('customer.post_signup');
    Route::get('orders/x/{invoice}', 'OrderController@view')->name('customer.view_order_unregistered');
    Route::get('orders/x/pdf/{invoice}', 'OrderController@pdf')->name('customer.order_pdf_unregistered');
    Route::post('orders/x/accept', 'OrderController@acceptOrder')->name('customer.order_accept_unregistered');
    Route::get('orders/x/cancel/{invoice}', 'OrderController@cancelOrder')->name('customer.order_cancel_unregistered');
    Route::get('payment/x', 'OrderController@paymentForm')->name('customer.paymentForm_unregistered');
    Route::post('payment/x', 'OrderController@storePayment')->name('customer.savePayment_unregistered');
    Route::post('/init-payment', 'OrderController@setPaymentDestination')->name('customer.set_payment_destination');

    Route::group(['middleware' => 'customer'], function() {
        Route::get('dashboard', 'LoginController@dashboard')->name('customer.dashboard');
        Route::get('logout', 'LoginController@logout')->name('customer.logout');

        Route::get('orders', 'OrderController@index')->name('customer.orders');
        Route::get('orders/a/{invoice}', 'OrderController@view')->name('customer.view_order');
        Route::get('orders/a/pdf/{invoice}', 'OrderController@pdf')->name('customer.order_pdf');
        Route::post('orders/a/accept', 'OrderController@acceptOrder')->name('customer.order_accept');
        Route::get('orders/a/cancel/{invoice}', 'OrderController@cancelOrder')->name('customer.order_cancel');
        Route::get('orders/return/{invoice}', 'OrderController@returnForm')->name('customer.order_return');
        Route::put('orders/return/{invoice}', 'OrderController@processReturn')->name('customer.return');

        Route::get('payment/a', 'OrderController@paymentForm')->name('customer.paymentForm');
        Route::post('payment/a', 'OrderController@storePayment')->name('customer.savePayment');

        Route::get('setting', 'FrontController@customerSettingForm')->name('customer.settingForm');
        Route::post('setting', 'FrontController@customerUpdateProfile')->name('customer.setting');
    });
});

Auth::routes();

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/manage', 'HomeController@homeManagement')->name('admin.home_management');

    Route::delete('/delete/{id}', 'HomeController@deleteFromSlider')->name('admin.home_management.slider.delete');
    Route::get('/manage/slider/add', 'HomeController@viewAddSlider')->name('admin.home_management.slider.view_add');
    Route::post('/manage/slider/add', 'HomeController@addToSlider')->name('admin.home_management.slider.add');
    Route::get('/manage/slider/show/{id}', 'HomeController@show')->name('admin.home_management.slider.show');
    Route::get('/manage/slider/edit/{id}', 'HomeController@viewEditSlider')->name('admin.home_management.slider.view_edit');
    Route::post('/manage/slider/edit', 'HomeController@editSlider')->name('admin.home_management.slider.edit');

    Route::delete('/{id}', 'HomeController@deleteFromFeatured')->name('admin.home_management.featured.delete');
    Route::post('/manage/featured/add', 'HomeController@addToFeatured')->name('admin.home_management.featured.add');

    Route::resource('admin', 'AdminController');

    
    Route::get('/product_variant/create/{id}', 'ProductVariantController@createVariant')->name('product_variant.create_variant');
    Route::get('/product_variant/get/{id}', 'ProductVariantController@get')->name('product_variant.get');
    Route::resource('category', 'CategoryController')->except(['create', 'show']);
    Route::resource('product', 'ProductController');
    Route::resource('product_variant', 'ProductVariantController')->except(['index', 'create', 'show']);

    Route::group(['prefix' => 'orders'], function() {
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('/orders_pending', 'OrderController@ordersPending')->name('orders.orders_pending');
        Route::get('/orders_done', 'OrderController@ordersDone')->name('orders.orders_done');
        Route::get('/{invoice}', 'OrderController@view')->name('orders.view');
        Route::get('/pending/{invoice}', 'OrderController@pendingPayment')->name('orders.make_pending');
        Route::get('/cancel/{invoice}', 'OrderController@cancelPayment')->name('orders.cancel_payment');
        Route::get('/payment/{invoice}', 'OrderController@acceptPayment')->name('orders.approve_payment');
        Route::post('/shipping', 'OrderController@shippingOrder')->name('orders.shipping');
        Route::get('/finish/{invoice}', 'OrderController@finishOrder')->name('orders.make_done');
        Route::delete('/{id}', 'OrderController@destroy')->name('orders.destroy');
        Route::get('/return/{invoice}', 'OrderController@return')->name('orders.return');
        Route::post('/return', 'OrderController@approveReturn')->name('orders.approve_return');
    });

    Route::group(['prefix' => 'reports'], function() {
        Route::get('/keuangan', 'HomeController@financeReport')->name('report.finance');
        Route::get('/product_statistic', 'HomeController@productStatistic')->name('report.product_statistic');
        Route::get('/order/pdf/{daterange}', 'HomeController@orderReportPdf')->name('report.order_pdf');
        Route::get('/return', 'HomeController@returnReport')->name('report.return');
        Route::get('/return/pdf/{daterange}', 'HomeController@returnReportPdf')->name('report.return_pdf');
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    protected $guarded = [];
    protected $appends = ['status_label'];

    public function getStatusLabelAttribute()
    {
        if ($this->status == 0) {
            return '<span class="badge badge-secondary">Draft</span>';
        } else {
            return '<span class="badge badge-success">Aktif</span>';
        }
    }

    public function setSlugAttribute($value) {
        if (static::whereSlug($slug = Str::slug($value))->exists()) {
            $slug = $this->incrementSlug($slug);
        }    
        $this->attributes['slug'] = $slug;
    }

    public function incrementSlug($slug) {
        $original = $slug;
        $count = 2;
        while (static::whereSlug($slug)->exists()) {
            $slug = "{$original}-" . $count++;
        }
        return $slug;
    }
    
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function variant()
    {
        return $this->hasMany(ProductVariant::class)->orderBy('price', 'ASC');;
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use App\Product;
use App\ProductVariant;
use App\Category;
use File;
use App\Jobs\ProductJob;
use App\Jobs\MarketplaceJob;

class ProductController extends Controller
{
    public function index()
    {
        if (Auth::user()->user_type_id == 1) {
            $product = Product::with(['category', 'variant'])->orderBy('created_at', 'DESC');
            $category = Category::orderBy('name', 'DESC')->get();
            $variant = ProductVariant::with(['product'])->get();
            if (request()->q != '') {
                $product = $product->where('name', 'LIKE', '%' . request()->q . '%');
            }
            $product = $product->paginate(10);
            return view('products.index', compact('product', 'category', 'variant'));
        }
    }

    public function create()
    {
        if (Auth::user()->user_type_id == 1) {
            $category = Category::orderBy('name', 'DESC')->get();
            return view('products.create', compact('category'));
        }
    }

    public function store(Request $request)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'category_id' => 'required|exists:categories,id',
                'name' => 'required|string|max:100',
                'description' => 'required',
                'status' => 'required|boolean',
                'image' => 'required|image|mimes:png,jpeg,jpg'
            ]);
            
            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $filename = time() . Str::slug($request->name) . '.' . $file->getClientOriginalExtension();
                $file->storeAs('public/products', $filename);

                $product = Product::create([
                    'category_id' => $request->category_id,
                    'name' => $request->name,
                    'slug' => $request->name,
                    'description' => $request->description,
                    'status' => $request->status,
                    'image' => $filename
                ]);

                $product_id = $product->id;

                $this->storeVariant($product_id, $request);

                return redirect(route('product.index'))->with(['success' => 'Produk dan Varian Baru Ditambahkan!']);
            }
        }
    }
    
    public function show($id)
    {
        $product = Product::where('id', $id)->with('variant', 'category')->first();
        return view('products.show', compact('product'));
    }

    public function storeVariant($product_id, Request $request)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'name_var' => 'required|string',
                'price' => 'required|integer',
                'weight' => 'required|integer',
                'minimum_stock' => 'required|integer',
                'stock' => 'required|integer',
                'image' => 'required|image|mimes:png,jpeg,jpg'
            ]);

            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $filename = time() . Str::slug($request->name_var) . '.' . $file->getClientOriginalExtension();
                $file->storeAs('public/variants', $filename);

                $product = ProductVariant::create([
                    'product_id' => $product_id,
                    'name' => $request->name_var,
                    'slug' => $request->name_var,
                    'price' => $request->price,
                    'weight' => $request->weight,
                    'minimum_stock' => $request->minimum_stock,
                    'stock' => $request->stock,
                    'image' => $filename
                ]);
            }
        }
    }

    public function edit($id)
    {
        if (Auth::user()->user_type_id == 1) {
            $product = Product::find($id);
            $category = Category::orderBy('name', 'DESC')->get();
            return view('products.edit', compact('product', 'category'));
        }
    }

    public function update(Request $request, $id)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'category_id' => 'required|exists:categories,id',
                'name' => 'required|string',
                'description' => 'required',
                'status' => 'required|boolean',
                'image' => 'nullable|image|mimes:png,jpeg,jpg'
            ]);

            $product = Product::find($id);
            $filename = $product->image;
            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $filename = time() . Str::slug($request->name) . '.' . $file->getClientOriginalExtension();
                $file->storeAs('public/products', $filename);
                File::delete(storage_path('app/public/products/' . $product->image));
            }

            $product->update([
                'category_id' => $request->category_id,
                'name' => $request->name,
                'description' => $request->description,
                'status' => $request->status,
                'image' => $filename
            ]);
            return redirect(route('product.index'))->with(['success' => 'Data Produk Diperbaharui!']);
        }
    }

    public function destroy($id)
    {
        if (Auth::user()->user_type_id == 1) {
            $product = Product::find($id);
            File::delete(storage_path('app/public/products/' . $product->image));
            $product->delete();

            $product_variants = ProductVariant::where('product_id', $id)->get();

            foreach($product_variants as $v) {
                $v->delete();
            }
            return redirect(route('product.index'))->with(['success' => 'Produk Sudah Dihapus!']);
        }
    }

    public function massUploadForm()
    {
        if (Auth::user()->user_type_id == 1) {
            $category = Category::orderBy('name', 'DESC')->get();
            return view('products.bulk', compact('category'));
        }
    }

    public function massUpload(Request $request)
    {
        if (Auth::user()->user_type_id == 1) {
            $this->validate($request, [
                'category_id' => 'required|exists:categories,id',
                'file' => 'required|mimes:xlsx'
            ]);

            if ($request->hasFile('file')) {
                $file = $request->file('file');
                $filename = time() . '-product.' . $file->getClientOriginalExtension();
                $file->storeAs('public/uploads', $filename);

                ProductJob::dispatch($request->category_id, $filename);
                return redirect()->back()->with(['success' => 'Upload Produk Dijadwalkan']);
            }
        }
    }

    public function uploadViaMarketplace(Request $request)
    {
        $this->validate($request, [
            'marketplace' => 'required|string',
            'username' => 'required|string'
        ]);

        MarketplaceJob::dispatch($request->username, 10);
        return redirect()->back()->with(['success' => 'Produk Dalam Antrian']);
    }

    
}

resources/views/products/bulk.blade.php
@extends('layouts.admin')

@section('title')
    <title>Mass Upload</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Product</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    @if (session('success'))
                        <div class="alert alert-success">{{ session('success') }}</div>
                    @endif
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Upload Via Excel</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('product.saveBulk') }}" method="post" enctype="multipart/form-data" >
                                @csrf
                                <div class="form-group">
                                    <label for="category_id">Kategori</label>
                                    <select name="category_id" class="form-control">
                                        <option value="">Pilih</option>
                                        @foreach ($category as $row)
                                        <option value="{{ $row->id }}" {{ old('category_id') == $row->id ? 'selected':'' }}>{{ $row->name }}</option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('category_id') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="file">File Excel</label>
                                    <input type="file" name="file" class="form-control" value="{{ old('file') }}" required>
                                    <p class="text-danger">{{ $errors->first('file') }}</p>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Upload</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/products/index.blade.php
@extends('layouts.admin')

@section('title')
<title>List Produk</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/administrator/home">Home</a></li>
        <li class="breadcrumb-item active"><a href="/administrator/product">Produk</a></li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                List Produk
                            </h4>
                        </div>
                        <div class="card-body">
                            @if (session('success'))
                            <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            @if (session('error'))
                            <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif
                            <span><a href="{{ route('product.create') }}"><button
                                        class="btn btn-primary mb-3 float-left">Tambah Produk</button></a></span>
                            <form action="{{ route('product.index') }}" method="get">
                                <div class="input-group mb-3 col-md-3 float-right">
                                    <input type="text" name="q" class="form-control" placeholder="Cari..."
                                        value="{{ request()->q }}">
                                    <div class="input-group-append">
                                        <button class="btn btn-secondary" type="button">Cari</button>
                                    </div>
                                </div>
                            </form>
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Nama Produk</th>
                                            <th>Nama Varian</th>
                                            <th>Stok</th>
                                            <th>Harga</th>
                                            <th>Berat</th>
                                            <th>Status</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($product as $row)
                                        @foreach ($row->variant as $subrow)
                                        <tr>
                                            <td>
                                                {{ $row->name }} <br>
                                                <div class="dropdown">
                                                    <button class="btn btn-secondary dropdown-toggle" type="button"
                                                        id="dropdownMenuButton" data-toggle="dropdown"
                                                        aria-haspopup="true" aria-expanded="false">
                                                        Action
                                                    </button>
                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                        <a class="dropdown-item"
                                                            href="{{ route('product.show', $row->id) }}">Detil
                                                            Produk</a>
                                                        <a class="dropdown-item"
                                                            href="{{ route('product.edit', $row->id) }}">Edit Produk</a>
                                                        <a class="dropdown-item"
                                                            href="{{ route('product.destroy', $row->id) }}"
                                                            onclick="return confirm('Hapus Produk?')">Hapus Produk</a>
                                                        <a class="dropdown-item"
                                                            href="{{ route('product_variant.create_variant', $row->id) }}">Tambah
                                                            Varian</a>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>{{ $subrow->name }}</td>
                                            <td>{{ $subrow->stock }}</td>
                                            <td>{{ $subrow->price }}</td>
                                            <td>{{ $subrow->weight }}</td>
                                            <td>{!! $row->status_label !!}</td>
                                            <td>
                                                <form action="{{ route('product_variant.destroy', $subrow->id) }}"
                                                    method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="#" data-toggle="modal" data-target="#show-variant" 
                                                        onclick="showVariant({{$subrow->id}})" class="btn btn-success btn-sm">Detil</a>
                                                    <a href="{{ route('product_variant.edit', $subrow->id) }}"
                                                        class="btn btn-warning btn-sm">Edit</a>
                                                    <button class="btn btn-danger btn-sm"
                                                        onclick="return confirm('Hapus Varian?')">Hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach                                        
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            {!! $product->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<div class="modal fade" tabindex="-1" id="show-variant" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detil Varian</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Nama Varian</th>
                                        <td id="variant_name"></td>
                                    </tr>
                                    <tr>
                                        <th>Harga</th>
                                        <td>Rp <span id="variant_price"></span></td>
                                    </tr>
                                    <tr>
                                        <th>Berat</th>
                                        <td id="variant_weight"></td>
                                    </tr>
                                    <tr>
                                        <th>Stok</th>
                                        <td id="variant_stock"></td>
                                    </tr>
                                    <tr>
                                        <th>Stok Minimum</th>
                                        <td id="variant_minimum"></td>
                                    </tr>
                                    <tr>
                                        <th>Gambar</th>
                                        <td>
                                            <img id="variant_image" src="" height="200px">
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Pembaharuan Terakhir</th>
                                        <td id="variant_updated"></td>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script>
    $('select').select2({
        theme: 'bootstrap4'
    });

    const table = document.querySelector('table');

    let headerCell = null;

    for (let row of table.rows) {
        const firstCell = row.cells[0];

        if (headerCell === null || firstCell.innerText !== headerCell.innerText) {
            headerCell = firstCell;
        } else {
            headerCell.rowSpan++;
            firstCell.remove();
        }
    }

    for (let row of table.rows) {
        const statusCell = row.cells[row.cells.length-2];

        if (headerCell === null || statusCell.innerText !== headerCell.innerText) {
            headerCell = statusCell;
        } else {
            headerCell.rowSpan++;
            statusCell.remove();
        }
    }

    function showVariant(id) {
        $.ajax({
            url: 'product_variant/get/' + id,
            type: 'GET',
            data: { id: id },
            dataType: 'JSON',
            success: function(res) {
                var date = new Date(res.updated_at);
                var filename = res.image;
                var src = "/storage/variants/" + filename;

                $("#variant_name").text(res.name);
                $("#variant_price").html(res.price);
                $("#variant_weight").text(res.weight);
                $("#variant_stock").text(res.stock);
                $("#variant_minimum").text(res.minimum_stock);
                $("#variant_image").attr('alt', res.name);
                $("#variant_image").attr('src', src);
                $("#variant_updated").text(date.toString());
            }
        });
    }
</script>
@endsection